MATERIAL_ACCUMULATION_CLASSES_DICT = {
    2: "box",
    6: "plastic",
    8: "tools",
    3: "pot",
    4: "fruit_vegetable_drygoods",
    11: "meat",
    12: "plant",
    10: "clothes",
    0: "others",
    7: "cabinet",
    1: "tables_chairs",
    9: "street_food_truck",
    5: "Tarpaulin",
}